trigger:
- main

stages:
- stage: Build

  jobs:
    - job: build_framework
    
      workspace:
        clean: all

      pool:
        name: rdc_test

      variables:
        venv: $(System.DefaultWorkingDirectory)/.venv
        python.version: "v3_12"

      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: "3.12"
          displayName: "Use Python $(python.version)"

        - script: |
            python3 -m venv $(venv)
            call $(venv)/Scripts/activate.bat
            python3 -m ensurepip --upgrade
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt
          workingDirectory: $(Build.SourcesDirectory)
          displayName: 'Install dependency'

        - script: |
            set Path=$(venv)/Scripts;%Path%
            python3 -m pip install pytest-azurepipelines
          env:
            PYTHON_HOME: ""
            VIRTUAL_ENV: $(venv)
          displayName: 'Install pytest-azure'

        - task: ArchiveFiles@2
          displayName: 'Archive files'
          inputs:
            rootFolderOrFile: $(System.DefaultWorkingDirectory)
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_$(python.version).zip
            replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Build Artifacts'
          inputs:
            ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                ArtifactName: 'production'
                publishLocation: 'Container'

            ${{ else }}:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                ArtifactName: 'development'
                publishLocation: 'Container'

        - task: DownloadPipelineArtifact@2
          displayName: 'Download Pipeline Production Artifact'
          inputs:
            ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
              artifact: production
              
            ${{ else }}:
              artifact: development

- stage: Release_Production
  dependsOn: Build
  jobs:
    - job: release_framework

      pool:
        name: rdc_test

      steps:
      - download: current
        artifact: production

- stage: Release_Development
  dependsOn: Build
  jobs:
    - job: release_framework

      pool:
        name: rdc_test

      steps:
      - download: current
        artifact: development

- stage: Test_Production
  dependsOn: Release_Production
  jobs:
    - job: run_test_production

      pool:
        name: rdc_test

      steps:
      - download: current
        artifact: production

- stage: Test_Development
  dependsOn: Release_Development
  jobs:
    - job: run_test_development

      pool:
        name: rdc_test

      steps:
      - download: current
        artifact: development





























        - script: |
            set Path=$(venv)/Scripts;%Path%
            python $(Build.SourcesDirectory)\test_applications\d_365\controler\userstory_pytest.py
          env:
            PYTHON_HOME: ""
            VIRTUAL_ENV: $(venv)
          displayName: 'Create execute'